[global]
pid = {ROOT}/var/run/php-fpm.pid
error_log = {ROOT}/var/log/php-fpm.log
daemonize = no

[www]
user = {USER}
group = {GROUP}
listen = {ROOT}/var/run/php-fpm.sock
listen.owner = {USER}
listen.group = {GROUP}
listen.mode = 0660

pm = static
pm.max_children = 5
pm.max_requests = 500