version: '3.8'

services:
  php-app:
    build: .

    # unique container_name
    container_name: app

    # unique image
    image: php-app:latest

    # unique ports
    ports:
      - "8080:8080"

    volumes:
      - var:/var/www/var
      - web:/var/www/web
    restart: always
    mem_limit: 128m
    memswap_limit: 128m

volumes:
  var:
  web: