[global]
pid = ${ROOT}/var/run/php-fpm.pid
error_log = ${ROOT}/var/log/php-fpm.log
daemonize = no

[www]
user = 10386
group = 10386
listen = ${LISTEN}
listen.owner = 10386
listen.group = 10386
listen.mode = 0660

pm = static
pm.max_children = 5