server.modules = (
    "mod_fastcgi",
    "mod_rewrite"
)

server.document-root = "{ROOT}/web"
server.port = 8080
server.pid-file = "{ROOT}/var/run/lighttpd.pid"
server.errorlog = "{ROOT}/var/log/lighttpd.log"
server.username = "{USER}"
server.groupname = "{GROUP}"

index-file.names = ( "index.php", "index.html" )

url.rewrite-if-not-file = (
    "^/(.*)$" => "/index.php/$1"
)

fastcgi.server = ( ".php" =>
    ((
        "socket" => "{ROOT}/var/run/php-fpm.sock",
        "broken-scriptfilename" => "enable"
    ))
)
