server.modules = (
    "mod_fastcgi",
    "mod_rewrite"
)

server.document-root = "/data/data/com.termux/files/home/www/test_app/web"
server.port = 8080
server.pid-file = "/data/data/com.termux/files/home/www/test_app/var/run/lighttpd.pid"
server.errorlog = "/data/data/com.termux/files/home/www/test_app/var/log/lighttpd.log"
server.username = "u0_a386"
server.groupname = "u0_a386"

index-file.names = ( "index.php", "index.html" )

url.rewrite-if-not-file = (
    "^/(.*)$" => "/index.php/$1"
)

fastcgi.server = ( ".php" =>
    ((
        "socket" => "/data/data/com.termux/files/home/www/test_app/var/run/php-fpm.sock",
        "broken-scriptfilename" => "enable"
    ))
)
